// eventbond-client/src/components/Navbar.tsx
import React from 'react';
import { Link, useNavigate, NavLink } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import LanguageSwitcher from './LanguageSwitcher';
import { useTranslation } from 'react-i18next';

const Navbar: React.FC = () => {
  const { isAuthenticated, user, logout: authLogout } = useAuth();
  const navigate = useNavigate();
  const { t } = useTranslation();

  const handleLogout = async () => {
    authLogout();
    navigate('/signin');
  };

  const linkStyle = "px-3 py-2 rounded-md text-sm font-medium transition-colors duration-150 ease-in-out";
  const activeLinkStyle = "bg-sky-600 text-white";
  const inactiveLinkStyle = "text-gray-300 hover:bg-sky-700 hover:text-white";

  return (
    <nav className="bg-sky-800 text-white shadow-md">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center">
            <Link to="/" className="text-2xl font-bold text-white hover:text-sky-200 transition-colors">
              {t('navbar.brand')}
            </Link>
          </div>
          <div className="hidden md:block">
            <div className="ml-10 flex items-baseline space-x-4">
              <NavLink 
                to="/events" 
                className={({ isActive }) => `${linkStyle} ${isActive ? activeLinkStyle : inactiveLinkStyle}`}
              >
                {t('navbar.events')}
              </NavLink>
              {isAuthenticated ? (
                <>
                  {user?.role === 'admin' && (
                    <NavLink 
                      to="/admin" 
                      className={({ isActive }) => `${linkStyle} ${isActive ? activeLinkStyle : inactiveLinkStyle}`}
                    >
                      {t('navbar.admin')}
                    </NavLink>
                  )}
                  <NavLink 
                    to="/bookings" 
                    className={({ isActive }) => `${linkStyle} ${isActive ? activeLinkStyle : inactiveLinkStyle}`}
                  >
                    {t('navbar.myBookings')}
                  </NavLink>
                  <span className="text-gray-300 px-3 py-2 text-sm font-medium">
                    {t('navbar.greeting', { name: user?.username })}
                  </span>
                  <button 
                    onClick={handleLogout} 
                    className={`${linkStyle} bg-pink-600 hover:bg-pink-700 text-white`}
                  >
                    {t('navbar.logout')}
                  </button>
                </>
              ) : (
                <>
                  <NavLink 
                    to="/signin" 
                    className={({ isActive }) => `${linkStyle} ${isActive ? activeLinkStyle : inactiveLinkStyle}`}
                  >
                    {t('navbar.signIn')}
                  </NavLink>
                  <NavLink 
                    to="/signup" 
                    className={`${linkStyle} bg-emerald-500 hover:bg-emerald-600 text-white`}
                  >
                    {t('navbar.signUp')}
                  </NavLink>
                </>
              )}
              <LanguageSwitcher />
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// eventbond-client/src/app/core/components/navbar/navbar.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService, User } from '../../services/auth.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit, OnDestroy {
  isLoggedIn: boolean = false;
  isAdmin: boolean = false;
  private userSubscription: Subscription | undefined;
  private adminSubscription: Subscription | undefined;

  constructor(public authService: AuthService, private router: Router) { }

  ngOnInit(): void {
    this.userSubscription = this.authService.currentUser$.subscribe((user: User | null) => {
      this.isLoggedIn = !!user;
    });
    this.adminSubscription = this.authService.isAdmin$.subscribe((isAdminStatus: boolean) => {
      this.isAdmin = isAdminStatus;
    });
  }

  logout(): void {
    this.authService.logout();
  }

  ngOnDestroy(): void {
    if (this.userSubscription) {
      this.userSubscription.unsubscribe();
    }
    if (this.adminSubscription) {
      this.adminSubscription.unsubscribe();
    }
  }
}

<nav class="bg-gray-800 text-white p-4 shadow-md">
  <div class="container mx-auto flex justify-between items-center">
    <a routerLink="/" class="text-2xl font-bold hover:text-gray-300">EventBond</a>

    <div class="hidden md:flex space-x-4 items-center">
      <a routerLink="/events" class="hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium">Events</a>
      <a *ngIf="isLoggedIn && isAdmin" routerLink="/admin" class="hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium">Admin Panel</a>
      <a *ngIf="isLoggedIn" routerLink="/bookings" class="hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium">My Bookings</a>
    </div>

    <div class="hidden md:flex items-center space-x-3">
      <ng-container *ngIf="!isLoggedIn; else loggedInActions">
        <a routerLink="/auth/signin" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out">Sign In</a>
        <a routerLink="/auth/signup" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out">Sign Up</a>
      </ng-container>
      <ng-template #loggedInActions>
        <button (click)="logout()" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out">Logout</button>
      </ng-template>
    </div>

    <div class="md:hidden flex items-center">
      <button class="outline-none mobile-menu-button">
        <svg class="w-6 h-6 text-white hover:text-gray-300" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
          <path d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>
    </div>
  </div>

  <div class="hidden mobile-menu">
    <ul class="">
      <li><a routerLink="/events" class="block text-sm px-2 py-4 hover:bg-gray-700 transition duration-300">Events</a></li>
      <li *ngIf="isLoggedIn && isAdmin"><a routerLink="/admin" class="block text-sm px-2 py-4 hover:bg-gray-700 transition duration-300">Admin Panel</a></li>
      <li *ngIf="isLoggedIn"><a routerLink="/bookings" class="block text-sm px-2 py-4 hover:bg-gray-700 transition duration-300">My Bookings</a></li>
      <li *ngIf="!isLoggedIn">
        <a routerLink="/auth/signin" class="block text-sm px-2 py-4 text-blue-400 hover:bg-gray-700 hover:text-blue-300 transition duration-300">Sign In</a>
      </li>
      <li *ngIf="!isLoggedIn">
        <a routerLink="/auth/signup" class="block text-sm px-2 py-4 text-green-400 hover:bg-gray-700 hover:text-green-300 transition duration-300">Sign Up</a>
      </li>
      <li *ngIf="isLoggedIn">
        <button (click)="logout()" class="block w-full text-left text-sm px-2 py-4 text-red-400 hover:bg-gray-700 hover:text-red-300 transition duration-300">Logout</button>
      </li>
    </ul>
  </div>
</nav>

<script>
  const btn = document.querySelector("button.mobile-menu-button");
  const menu = document.querySelector(".mobile-menu");

  btn.addEventListener("click", () => {
    menu.classList.toggle("hidden");
  });
</script>
